WIP 3

diff --git a/mk/makei b/mk/makei
--- a/mk/makei
+++ b/mk/makei
@@ -22,31 +22,53 @@
 # ----------------------------------
 # Colors
 # ----------------------------------
-BOLD='\033[1m'
-NOCOLOR='\033[0m'
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-ORANGE='\033[0;33m'
-BLUE='\033[0;34m'
-PURPLE='\033[0;35m'
-CYAN='\033[0;36m'
-LIGHTGRAY='\033[0;37m'
-DARKGRAY='\033[1;30m'
-LIGHTRED='\033[1;31m'
-LIGHTGREEN='\033[1;32m'
-YELLOW='\033[1;33m'
-LIGHTBLUE='\033[1;34m'
-LIGHTPURPLE='\033[1;35m'
-LIGHTCYAN='\033[1;36m'
-WHITE='\033[1;37m'
+# COLORS=true
+COLORS=false
+if [ "$COLORS" = true ]; then
+    BOLD='\033[1m'
+    NOCOLOR='\033[0m'
+    RED='\033[0;31m'
+    GREEN='\033[0;32m'
+    ORANGE='\033[0;33m'
+    BLUE='\033[0;34m'
+    PURPLE='\033[0;35m'
+    CYAN='\033[0;36m'
+    LIGHTGRAY='\033[0;37m'
+    DARKGRAY='\033[1;30m'
+    LIGHTRED='\033[1;31m'
+    LIGHTGREEN='\033[1;32m'
+    YELLOW='\033[1;33m'
+    LIGHTBLUE='\033[1;34m'
+    LIGHTPURPLE='\033[1;35m'
+    LIGHTCYAN='\033[1;36m'
+    WHITE='\033[1;37m'
+else
+    BOLD=''
+    NOCOLOR=''
+    RED=''
+    GREEN=''
+    ORANGE=''
+    BLUE=''
+    PURPLE=''
+    CYAN=''
+    LIGHTGRAY=''
+    DARKGRAY=''
+    LIGHTRED=''
+    LIGHTGREEN=''
+    YELLOW=''
+    LIGHTBLUE=''
+    LIGHTPURPLE=''
+    LIGHTCYAN=''
+    WHITE=''
+fi
 
 exitCode=0
 
 makeOpts=$*
 srcDir="$(pwd)"
 
-rm -rf "${srcDir}/log/output.log"
-rm -rf "${srcDir}/log/joblog.json"
+rm -rf "${srcDir}/logs/output.log"
+rm -rf "${srcDir}/logs/joblog.json"
 
 retrieve_from_iproj() {
     local key=$1
@@ -131,7 +153,10 @@ recursive_generate() {
     local parentCcsid=$3
     local objlibraw
     local tgtCcsid
-    cd "$dir" || ( echo "${dir} not found"; exit 1)
+    cd "$dir" || (
+        echo "${dir} not found"
+        exit 1
+    )
 
     if [[ -f ".ibmi.json" ]]; then
         objlibraw=$(retrieve_from_ibmijson ".ibmi.json" "build.objlib" "")
@@ -165,18 +190,18 @@ recursive_generate() {
                 cd ..
             fi
         done
-    fi;
+    fi
 }
 
 echo -e "${BLUE}Generating makefile for build variables at ${BUILDVARSMK}${NOCOLOR}"
 echo
-recursive_generate "$srcDir" "$objlib"  "$tgtCcsid"
+recursive_generate "$srcDir" "$objlib" "$tgtCcsid"
 ibmijsonError=$?
 # cat $BUILDVARSMK
 
 if test $ibmijsonError -eq 0; then
-    echo -e ">> ${GREEN}"make BUILDVARSMKPATH="${BUILDVARSMK}" -f /QOpenSys/pkgs/lib/bob/Makefile "$makeOpts""${NOCOLOR}"
-    make BUILDVARSMKPATH="${BUILDVARSMK}" "$makeOpts"
+    echo -e ">> ${GREEN}"make BUILDVARSMKPATH="${BUILDVARSMK}" COLOR_TTY="${COLORS}" -f /QOpenSys/pkgs/lib/bob/Makefile "$makeOpts""${NOCOLOR}"
+    make BUILDVARSMKPATH="${BUILDVARSMK}" COLOR_TTY="${COLORS}" "$makeOpts"
     echo
 
     exitCode=$?
